### ISSUE TITLE
[1.12.2] Two little issues

### ISSUE THREAD

**Issue by wamc2017** [Flaxbeard/QuestionablyImmersive#1]
Hi,

first thanks for the mod. I compiled the mod myself, because the version on curse got some Immersive Petroleum files inside the jar and it crashed with some missing javafx error, which is already resolved in the last commit...

The first issue is, there is some coal block outside the gui, which should be not there I guess:
![2018-05-04_00 53 20](https://user-images.githubusercontent.com/33242447/39606437-b91b24ac-4f35-11e8-8aa8-2d3f472910b9.png)

The recipe in the Engineer's manual is wrong:
![2018-05-04_00 53 45](https://user-images.githubusercontent.com/33242447/39606463-dfff8572-4f35-11e8-8a3a-9282f3b6b524.png)

Should be the following I guess:
18x Steel Scaffolding
6x Pipe
24x Steel Sheetmetal
12x Light Engineering block
12x Piston

Thanks for looking into it. :)

Best regards
wamc2017

**Comment by wamc2017** [comment]
Oh and I tried to create a fullsize coke oven, but it stopped after 100 batteries, instead after 250 (the complete area is chunkloaded)
Personally 100 is enough, but if there's 250 in the book, people maybe complain about it... :smile:

**Comment by Flaxbeard** [comment]
Good catches! Thanks for the bug reports.

- [x] Fix mismatch between max coke oven side and number listed in the Engineer's Manual.
- [x] Fix material requirements in the Engineer's Manual.
- [x] Make sure hidden slots are actually moved offscreen.
