### ISSUE TITLE
Book recipie is different from the picture

### ISSUE THREAD

**Issue by Dragonracer1973** [Flaxbeard/QuestionablyImmersive#10]
currently the book recipe calls for completely different materials, then what is in the picture, and are as follows 11 steel scaffolding, 6 treated wood fence, 4 fluid pipes, 1 redstone engineering, 2 light engineering, 2 heavy engineering, 2 blocks of steel, and 4 steel sheetmetal. The structure can be made as long as you follow the visual picture as opposed to the "?" recipie

![2019-05-21_11 50 33_2](https://user-images.githubusercontent.com/50302305/58115003-b3ad6a00-7bbe-11e9-88f2-f3fae8bf3453.png) 

I am playing on a server on Absolute Immersive ver 1.5 of the pack and 0.1.0 of the mod

**Comment by Flaxbeard** [comment]
Fixed
