### ISSUE TITLE
[1.14.4]Issue: Game crashes at odd times. Only QI & IE installed

### ISSUE THREAD

**Issue by McMasterx** [Flaxbeard/QuestionablyImmersive#14]
https://hastebin.com/zuwuvovohu.pl
First time it was while placing scaffolding to make a press, then it was as I was forming the press. This latest one, I managed to form the Press, but then went Afk and it just crashed later anyway

**Comment by Flaxbeard** [comment]
Should be fixed in 0.1.3, thanks!
